/* DEKKAN i18n — Arabic (default) + English, RTL/LTR flip, persisted.
 * Static text:  [data-i18n]  = textContent
 *                [data-i18n-ph]  = placeholder
 *                [data-i18n-title] = title / aria-label
 * Dynamic text (app.js): T.t('key')
 * A change fires 'dekkan:lang' so views re-render their text.
 */
'use strict';
(function () {
  const LS_LANG = 'dekkan.lang';

  const AR = {
    'app.name': 'دكان', 'app.tagline': 'صندوق + مخزون + ديون لمحلك',
    'cashbox.label': 'رصيد الصندوق', 'today': 'اليوم: ',
    'curr': 'د.ت',

    'tab.sell': 'البيع', 'tab.stock': 'المخزون', 'tab.debts': 'الديون', 'tab.clients': 'الزبائن',
    'tab.report': 'التقرير',
    'tab.cashbox': 'الخزينة',
    'tab.settings': 'الإعدادات',

    'sell.title': 'البيع',
    'sell.sub': 'بيع نقدي أو بالدين — كل شيء يُحسب وحدو',
    'sell.refund': 'استرجاع',
    'refund.title': 'استرجاع منتوج',
    'refund.qty': 'الكمية', 'refund.reason': 'السبب',
    'refund.reasonPh': 'اختياري — مثل: سلعة معيبة',
    'refund.go': 'تسجيل الاسترجاع',
    'free.title': 'سلعة / خدمة بدون مخزون',
    'free.namePh': 'الاسم — مثل: قهوة، حلاقة', 'free.pricePh': 'الثمن',
    'free.add': 'إضافة', 'free.qty': 'كمية',
    'basket.title': 'السلة',
    'disc.pct': 'خصم %', 'disc.flat': 'خصم ثابت',
    'credit.label': 'اسم الزبون',
    'credit.ph': 'للبيع بالدين أو الدفع الناقص',
    'cashier.label': 'البائع', 'cashier.ph': 'اللي صبّع البيع — يظهر في تقرير اليوم',
    'sell.paid': 'المبلغ المدفوع',
    'sell.paidPh': 'الفلوس اللي عطاها الزبون',
    'sell.change': 'الباقي للزبون:',
    'sell.exact': 'دفع بالضبط — بلا باقي',
    'sell.rest': 'الباقي على الزبون:',
    'sell.restNeedName': 'اكتب اسم الزبون',
    'sell.onCredit': 'بالدِّين على:',
    'sell.due': 'المطلوب دفعه',
    'sell.items': 'قطع',
    'sell.discount': 'خصم',
    'sell.nothingYet': 'أضف منتوجًا للسلة',
    'sell.nextClient': 'الزبون القادم #',
    'sell.lineTotal': 'المجموع',
    'sell.go': 'تسجيل البيع',
    'stock.left': 'متبقية', 'stock.leftEn': 'left',
    'basket.empty': 'السلة فارغة — اضغط على منتوج',
    'sell.none': 'لا منتوجات بعد — أضف واحدًا من تبويب المخزون',
    'sell.searchPh': 'ابحث عن منتوج بالاسم...',
    'sell.lowBanner': '⚠ {n} منتوج قارب على النفاد — اضغط لإعادة التخزين',

    'stock.title': 'المخزون', 'stock.sub': 'كل منتوج بثمنيه: شراء وبيع',
    'stock.new': 'منتج جديد', 'stock.edit': 'تعديل',
    'stock.name': 'الاسم', 'stock.buy': 'ثمن الشراء', 'stock.sell': 'ثمن البيع',
    'stock.qty': 'الكمية', 'stock.lowAt': 'تنبيه عند (كمية قليلة)',
    'stock.empty': 'لا منتوجات — أضف أول منتوج',
    'common.cancel': 'إلغاء', 'common.save': 'حفظ',

    'debts.title': 'الديون', 'debts.sub': 'الدفتر الرقمي — من عليه وكم',
    'debts.new': 'دين جديد',
    'debts.name': 'اسم الزبون', 'debts.amount': 'المبلغ',
    'debts.phone': 'الهاتف (اختياري)', 'debts.note': 'ملاحظة',
    'debts.pay': 'سداد', 'debts.paid': 'مدفوع', 'debts.settled': 'مُسَدَّس',
    'debts.empty': 'لا ديون — ممتاز',
    'debts.payTitle': 'سداد',

    'clients.head': 'الزبائن', 'clients.sub': 'كل زبون محفوظ: بياناته، مشترياته، الاسترجاعات، والديون',
    'clients.empty': 'لا يوجد زبائن محفوظين بعد', 'clients.noHistory': 'لا حركة لهذا الزبون بعد',
    'clients.purchases': 'المشتريات', 'clients.refunds': 'الاسترجاعات', 'clients.owed': 'الباقي عليه',
    'clients.purchase': 'شراء', 'clients.refund': 'استرجاع',
    'clients.debtAdd': 'دين جديد', 'clients.debtPay': 'سداد دين',

    'report.title': 'تقرير اليوم', 'report.sub': 'القصة الكاملة للفلوس',
    'report.check': 'عدّ الصندوق',
    'report.checkPh': 'عدّ الفلوس في الصندوق الآن',
    'report.checkGo': 'تسجيل العدّ',
    'report.expected': 'الصندوق يجب أن يحتوي: ',
    'report.movements': 'حركة اليوم', 'report.undo': 'تراجع عن آخر بيع',
    'report.noCashier': 'لا يوجد بائعون بعد — اذكر اسم البائع في صفحة البيع',
    'report.sales': 'مبيعات',
    'report.matched': 'مطابق', 'report.diff': 'فرق: ',
    'report.today': 'اليوم', 'report.chip.closed': 'نهاية ذلك اليوم',
    'report.noChecks': 'لم تعدَّ الصندوق اليوم بعد', 'report.left': 'باقي',
    'report.noMoves': 'لا حركة اليوم بعد',
    'report.chip.start': 'فلوس الصبح', 'report.chip.now': 'في الصندوق الآن',
    'report.chip.sales': 'مبيعات اليوم', 'report.chip.refunds': 'استرجاعات',
    'report.chip.expenses': 'مصاريف', 'report.chip.buys': 'شراء مخزون',
    'report.chip.profit': 'ربح اليوم', 'report.chip.inventory': 'قيمة المخزون',
    'report.chip.debts': 'ديون مفتوحة',
    'report.chip.low': 'بضاعة قليلة',

    'cashbox.title': 'الخزينة', 'cashbox.sub': 'فلوس تدخل الصندوق وفلوس تخرج',
    'cashbox.now': 'في الصندوق الآن',
    'cashbox.inToday': 'دخل اليوم', 'cashbox.outToday': 'خروج اليوم',
    'cashbox.inTitle': 'إيداع فلوس', 'cashbox.amount': 'المبلغ',
    'cashbox.inSrc': 'المصدر (من وين)', 'cashbox.inGo': 'إيداع',
    'cashbox.outTitle': 'سحب فلوس', 'cashbox.outPurpose': 'الغرض (علاش)', 'cashbox.outGo': 'سحب',
    'cashbox.cats': 'الفئات', 'cashbox.catsIn': 'فئات المصدر', 'cashbox.catsOut': 'فئات الغرض',
    'cashbox.catPh': 'فئة جديدة…', 'cashbox.catAdd': 'إضافة',
    'cashbox.noCats': 'ما زال ما فمّا فئات — زيد وحدة من فوق',
    'kind.sale': 'بيع', 'kind.debtPay': 'سداد دين', 'kind.refund': 'استرجاع',
    'kind.buy': 'شراء مخزون', 'kind.expense': 'مصروف', 'kind.income': 'إيراد',
    'kind.check': 'عدّ صندوق',

    'settings.title': 'الإعدادات', 'settings.sub': 'المحل، المظهر، اللغة، خيارات اليوم',
    'settings.sect.shop': 'المحل', 'settings.sect.look': 'المظهر',
    'settings.sect.lang': 'اللغة', 'settings.sect.behave': 'السلوك',
    'settings.sect.day': 'إدارة اليوم', 'settings.sect.about': 'عن التطبيق', 'settings.sect.pin': 'الحماية',
    'settings.pinTitle': 'قفل المالك (أرقام)', 'settings.pinHint': 'يُطلب قبل الاسترجاع والتراجع وإغلاق اليوم والاستيراد والحذف',
    'settings.pinSet': 'تعيين / تغيير', 'settings.pinClear': 'إزالة القفل',
    'settings.pinActive': 'القفل مفعّل — العمليات الحساسة تطلب الرمز',
    'settings.pinOff': 'بدون قفل — أي عملية ممكنة فوراً',
    'settings.theme': 'شكل الدكان', 'settings.version': 'النسخة',
    'settings.storage': 'المساحة المستعملة',
    'theme.souk': 'الذهبي', 'theme.mint': 'الزمرد', 'theme.royal': 'البنفسجي',
    'toast.themeOk': 'تم تغيير شكل الدكان',
    'auth.title': 'حساب الدكان',
    'auth.sub': 'احفظ متجرك على السحابة وتصرف من أي جهاز — حساب واحد لكل محل',
    'auth.namePh': 'اسم المحل',
    'auth.email': 'البريد الإلكتروني', 'auth.password': 'كلمة السر',
    'auth.submitLogin': 'دخول', 'auth.submitRegister': 'إنشاء الحساب',
    'auth.switchToRegister': 'ما عندك حساب؟ سجّل',
    'auth.switchToLogin': 'عندك حساب؟ دخول',
    'auth.skip': 'بدون حساب (محلي فقط)',
    'auth.welcome': 'مرحباً بك في دكانك',
    'auth.synced': 'تزامنت بياناتك مع السحابة',
    'auth.err.offline': 'لا يمكن الوصول للخادم — تحقق من الإنترنت',
    'auth.err.badCredentials': 'البريد أو كلمة السر غير صحيحة',
    'auth.err.emailTaken': 'هذا البريد مسجّل قبل',
    'auth.err.invalidEmail': 'اكتب بريداً صحيحاً',
    'auth.err.shortPass': 'كلمة السر قصيرة (6 أحرف على الأقل)',
    'auth.err.shortName': 'اكتب اسم المحل (حرفين على الأقل)',
    'auth.err.generic': 'حدث خطأ — أعد المحاولة',
    'settings.sect.account': 'الحساب',
    'settings.accountEmail': 'البريد', 'settings.accountMode': 'وضع الحساب',
    'settings.accountSigned': 'متصّل بالسحابة', 'settings.accountLocal': 'محلي — بلا حساب',
    'settings.signOut': 'تسجيل الخروج',
    'toast.signedOut': 'خرجت من الحساب',
    'settings.shopName': 'اسم المحل', 'settings.startCash': 'فلوس بداية اليوم',
    'settings.startCashHint': 'بداية اليوم تُغيّر عند فتح صندوق جديد (إغلاق اليوم).',
    'settings.discount': 'الخصم مسموح', 'settings.discountHint': 'تظهر حقول الخصم في البيع',
    'settings.refund': 'الاسترجاع مسموح', 'settings.refundHint': 'تظهر خاصية الاسترجاع',
    'settings.closeDay': 'إغلاق يوم اليوم',
    'settings.export': 'حفظ نسخة (JSON)', 'settings.import': 'استرجاع نسخة (JSON)',
    'settings.reset': 'مسح كل شيء وإعادة البدء',
    'settings.autosave': 'الحفظ تلقائي على كل عملية. النسخة الاحتياطية مزدوجة داخل المتصفح.',
    'settings.language': 'لغة الواجهة',

    'pin.title': 'رمز المالك', 'pin.wrong': 'الرمز خطأ — حاول مجدداً',
    'pin.badFormat': 'الرمز 4 إلى 6 أرقام فقط',
    'pin.saved': 'تم حفظ رمز المالك', 'pin.cleared': 'أُزيل قفل المالك',
    'pin.confirm': 'اكتب الرمز الحالي للتأكيد',
    'pin.refund': 'استرجاع فلوس — رمز المالك؟',
    'pin.day': 'إغلاق اليوم — رمز المالك؟',
    'pin.undo': 'التراجع عن آخر بيع — رمز المالك؟',
    'pin.import': 'استيراد نسخة كاملة — رمز المالك؟',
    'pin.reset': 'مسح كل شيء — رمز المالك؟',
    'pin.debt': 'حذف دين — رمز المالك؟',
    'pin.fire': 'إنهاء عقد موظف — رمز المالك؟',
    'pin.clear': 'مسح', 'pin.ok': 'موافق',

    'toast.couldntSave': 'تعذّر الحفظ',
    'toast.saleCancelled': 'أُلغي البيع',
    'toast.saleOk': 'سُجّل البيع', 'toast.saleCredit': 'سُجّل على الدين: ',
    'toast.saleRest': 'سُجّل البيع، والباقي على: ',
    'toast.change': 'أعطِ الزبون الباقي:',
    'toast.paidBad': 'المبلغ المدفوع غير صحيح',
    'toast.restName': 'الباقي يحتاج اسم الزبون',
    'toast.freeName': 'اكتب اسم السلعة',
    'toast.freePrice': 'الثمن يجب أن يكون صفرًا أو أكثر',
    'toast.freeQty': 'الكمية يجب أن تكون 1 على الأقل',
    'toast.refundPick': 'اختر منتوجًا للاسترجاع',
    'toast.refundOk': 'تم الاسترجاع',
    'toast.prodName': 'اكتب اسم المنتوج', 'toast.prodPrice': 'اكتب ثمن البيع',
    'toast.savedOk': 'تم الحفظ',
    'toast.debtName': 'اكتب الاسم والمبلغ', 'toast.debtOk': 'سُجّل الدين',
    'toast.amount': 'اكتب المبلغ', 'toast.payOk': 'تم السداد',
    'toast.payOver': 'المبلغ أكبر من الباقي على الزبون: ',
    'toast.cashIn': 'تم الإيداع في الصندوق', 'toast.cashOut': 'تم السحب من الصندوق',
    'toast.catAdded': 'أُضيفت الفئة', 'toast.catDup': 'هذه الفئة موجودة أصلاً',
    'toast.noStock': 'ما فمّاش مخزون من هذا المنتوج',
    'toast.maxStock': 'الكمية ما تفوتش المخزون الحالي: ',
    'toast.checkAmt': 'اكتب العدد الذي عاددته', 'toast.checkOk': 'سُجّل العدّ',
    'toast.dayClosed': 'أُغلق اليوم، وبدأ يوم جديد بنفس الرصيد',
    'toast.undoConfirm': 'تراجع عن آخر بيع؟ يُرجع البضاعة والفلوس ويحذف الدين الذي خلقه.',
    'toast.undoOk': 'أُلغي آخر بيع', 'toast.nothingUndo': 'لا يوجد بيع للتراجع عنه',
    'toast.debtDeleted': 'حُذف من السجل',
    'toast.resetConfirm': 'مسح كل بيانات المحل؟ هذا لا يُرجع. (يمكنك حفظ نسخة أولًا)',
    'toast.resetOk': 'بدأنا من جديد',
    'toast.importConfirm': 'استرجاع هذه النسخة؟ ستُستبدل بيانات المحل الحالية فورًا.',
    'toast.importOk': 'تمت الاستعادة بنجاح', 'toast.importBad': 'هذا الملف ليس نسخة صالحة',
    'toast.restock': 'أُضيف للمخزون',

    'receipt.title': 'الفاتورة', 'receipt.client': 'الزبون',
    'receipt.close': 'تمام', 'receipt.print': 'طباعة', 'receipt.thanks': 'شكراً لزيارتكم',
    'receipt.total': 'المجموع', 'receipt.paid': 'المدفوع',

    'tab.employees': 'الموظفون', 'tab.monthly': 'الشهري',
    'staff.head': 'الموظفون',
    'staff.sub': 'فريقك ورواتبهم — أضف، عدّل، أنهِ العقد',
    'monthly.head': 'المراجعة الشهرية', 'monthly.sub': 'الدخل والخسائر والربح — والرواتب داخلها',
    'staff.perMonth': 'في الشهر',
    'staff.wins': 'الدخل (داخل)', 'staff.losses': 'الخسائر (خارج)', 'staff.profit': 'الربح',
    'staff.sales': 'المبيعات', 'staff.debtPays': 'سداد ديون', 'staff.incomes': 'ودائع أخرى',
    'staff.refunds': 'المردودات', 'staff.buys': 'شراء مخزون', 'staff.expenses': 'المصاريف',
    'staff.salaries': 'الرواتب', 'staff.moves': 'حركة', 'staff.dayInOut': 'داخل / خارج',
    'staff.team': 'الفريق',
    'staff.add': 'أضف موظفاً', 'staff.new': 'موظف جديد', 'staff.edit': 'تعديل',
    'staff.empty': 'لا يوجد موظفون بعد — أضف أول موظف',
    'staff.name': 'الاسم', 'staff.type': 'الصنف / المنصب', 'staff.salary': 'الراتب الشهري',
    'staff.phone': 'الهاتف (اختياري)', 'staff.note': 'ملاحظة', 'staff.hired': 'التحاق',
    'staff.fire': 'إنهاء العمل', 'staff.fired': 'منتهي العقد',
    'toast.empSaved': 'تم حفظ الموظف', 'toast.empFired': 'تم إنهاء عمل الموظف',
    'toast.empFields': 'اكتب الاسم والصنف', 'toast.empSalary': 'راتب غير صالح'
  };

  const EN = {
    'app.name': 'Dekkan', 'app.tagline': 'cash box + stock + debts for your shop',
    'cashbox.label': 'Cash in box', 'today': 'Today: ',
    'curr': 'TND',

    'tab.sell': 'Sell', 'tab.stock': 'Stock', 'tab.debts': 'Debts', 'tab.clients': 'Clients',
    'tab.report': 'Report',
    'tab.cashbox': 'Cash box',
    'tab.settings': 'Settings',

    'sell.title': 'Sell',
    'sell.sub': 'Cash or credit — everything counts itself',
    'sell.refund': 'Refund',
    'refund.title': 'Refund an item',
    'refund.qty': 'Qty', 'refund.reason': 'Reason',
    'refund.reasonPh': 'optional — e.g. damaged item',
    'refund.go': 'Record refund',
    'free.title': 'Item / service without stock',
    'free.namePh': 'name — e.g. coffee, haircut', 'free.pricePh': 'price',
    'free.add': 'Add', 'free.qty': 'Qty',
    'basket.title': 'Basket',
    'disc.pct': 'Discount %', 'disc.flat': 'Discount TND',
    'credit.label': 'Customer name',
    'credit.ph': 'for credit or part payment',
    'cashier.label': 'Cashier', 'cashier.ph': 'who rang the sale — shows in today\'s report',
    'sell.paid': 'Cash handed over',
    'sell.paidPh': 'what the customer gave you',
    'sell.change': 'Change to give back:',
    'sell.exact': 'Exact money — no change',
    'sell.rest': 'Rest on the customer:',
    'sell.restNeedName': 'type the customer name',
    'sell.onCredit': 'On credit to:',
    'sell.due': 'Amount due',
    'sell.items': 'item(s)',
    'sell.discount': 'discount',
    'sell.nothingYet': 'add a product to the basket',
    'sell.nextClient': 'Next customer #',
    'sell.lineTotal': 'Line total',
    'sell.go': 'Record sale',
    'stock.left': 'left', 'stock.leftEn': 'left',
    'basket.empty': 'Basket empty — tap a product',
    'sell.none': 'No products yet — add one from Stock',
    'sell.searchPh': 'Search products by name...',
    'sell.lowBanner': '⚠ {n} product left in thin supply — tap to restock',

    'stock.title': 'Stock', 'stock.sub': 'Every product, two prices: buy & sell',
    'stock.new': 'New product', 'stock.edit': 'Edit',
    'stock.name': 'Name', 'stock.buy': 'Buy price', 'stock.sell': 'Sell price',
    'stock.qty': 'Qty', 'stock.lowAt': 'Low-stock alert at',
    'stock.empty': 'No products — add your first one',
    'common.cancel': 'Cancel', 'common.save': 'Save',

    'debts.title': 'Debts', 'debts.sub': 'The digital notebook — who owes & how much',
    'debts.new': 'New debt',
    'debts.name': 'Customer name', 'debts.amount': 'Amount',
    'debts.phone': 'Phone (optional)', 'debts.note': 'Note',
    'debts.pay': 'Pay', 'debts.paid': 'paid', 'debts.settled': 'Settled',
    'debts.empty': 'No debts — clean',
    'debts.payTitle': 'Pay',

    'clients.head': 'Clients', 'clients.sub': 'Every saved client: data, purchases, refunds, and debts',
    'clients.empty': 'No saved clients yet', 'clients.noHistory': 'No movement for this client yet',
    'clients.purchases': 'Purchases', 'clients.refunds': 'Refunds', 'clients.owed': 'Still owes',
    'clients.purchase': 'Purchase', 'clients.refund': 'Refund',
    'clients.debtAdd': 'New debt', 'clients.debtPay': 'Debt paid',

    'report.title': "Today's report", 'report.sub': 'The full money story',
    'report.check': 'Count the box',
    'report.checkPh': 'count the cash in the box now',
    'report.checkGo': 'Record count',
    'report.expected': 'The box should hold: ',
    'report.movements': "Today's moves", 'report.undo': 'Undo last sale',
    'report.noCashier': 'No cashier yet — type a name on the sell page',
    'report.sales': 'sales',
    'report.matched': 'Matches', 'report.diff': 'diff: ',
    'report.today': 'Today', 'report.chip.closed': 'End of that day',
    'report.noChecks': 'No box counts yet today', 'report.left': 'left',
    'report.noMoves': 'No movement today',
    'report.chip.start': 'MORNING CASH', 'report.chip.now': 'IN BOX NOW',
    'report.chip.sales': "TODAY'S SALES", 'report.chip.refunds': 'REFUNDS',
    'report.chip.expenses': 'EXPENSES', 'report.chip.buys': 'STOCK BUYS',
    'report.chip.profit': "TODAY'S PROFIT", 'report.chip.inventory': 'INVENTORY',
    'report.chip.debts': 'OPEN DEBTS',
    'report.chip.low': 'LOW STOCK',

    'cashbox.title': 'Cash box', 'cashbox.sub': 'Money in and out of the box',
    'cashbox.now': 'In the box now',
    'cashbox.inToday': 'In today', 'cashbox.outToday': 'Out today',
    'cashbox.inTitle': 'Cash in', 'cashbox.amount': 'Amount',
    'cashbox.inSrc': 'Source (from where)', 'cashbox.inGo': 'Add in',
    'cashbox.outTitle': 'Cash out', 'cashbox.outPurpose': 'Purpose (why)', 'cashbox.outGo': 'Take out',
    'cashbox.cats': 'Categories', 'cashbox.catsIn': 'Source categories', 'cashbox.catsOut': 'Purpose categories',
    'cashbox.catPh': 'New category…', 'cashbox.catAdd': 'Add',
    'cashbox.noCats': 'No categories yet — add one above',

    'kind.sale': 'SALE', 'kind.debtPay': 'DEBT PAY', 'kind.refund': 'REFUND',
    'kind.buy': 'STOCK BUY', 'kind.expense': 'EXPENSE', 'kind.income': 'INCOME',
    'kind.check': 'BOX COUNT',

    'settings.title': 'Settings', 'settings.sub': 'Shop, look, language, day options',
    'settings.sect.shop': 'The shop', 'settings.sect.look': 'The look',
    'settings.sect.lang': 'Language', 'settings.sect.behave': 'Behaviour',
    'settings.sect.day': 'The day', 'settings.sect.about': 'The app', 'settings.sect.pin': 'Security',
    'settings.pinTitle': 'Owner lock (digits)', 'settings.pinHint': 'asked before refunds, undo, close day, import and deletions',
    'settings.pinSet': 'Set / change', 'settings.pinClear': 'Remove lock',
    'settings.pinActive': 'Lock is ON — sensitive actions ask for the code',
    'settings.pinOff': 'No lock — everything runs immediately',
    'settings.theme': 'Shop look', 'settings.version': 'Version',
    'settings.storage': 'Storage used',
    'theme.souk': 'Gold Souk', 'theme.mint': 'Midnight Mint', 'theme.royal': 'Indigo Night',
    'toast.themeOk': 'Shop look changed',
    'auth.title': 'Dekkan account',
    'auth.sub': 'Save your shop to the cloud and run it from any device — one account per shop',
    'auth.namePh': 'Shop name',
    'auth.email': 'Email', 'auth.password': 'Password',
    'auth.submitLogin': 'Sign in', 'auth.submitRegister': 'Create account',
    'auth.switchToRegister': 'No account? Create one',
    'auth.switchToLogin': 'Have an account? Sign in',
    'auth.skip': 'Continue without an account (local only)',
    'auth.welcome': 'Welcome to your shop',
    'auth.synced': 'Your shop synced to the cloud',
    'auth.err.offline': 'Cannot reach the server — check your connection',
    'auth.err.badCredentials': 'Wrong email or password',
    'auth.err.emailTaken': 'This email already has an account',
    'auth.err.invalidEmail': 'Enter a valid email',
    'auth.err.shortPass': 'Password is too short (6 characters minimum)',
    'auth.err.shortName': 'Enter your shop name (2 characters minimum)',
    'auth.err.generic': 'Something went wrong — try again',
    'settings.sect.account': 'Account',
    'settings.accountEmail': 'Email', 'settings.accountMode': 'Account mode',
    'settings.accountSigned': 'Signed in to the cloud', 'settings.accountLocal': 'Local — no account',
    'settings.signOut': 'Sign out',
    'toast.signedOut': 'Signed out',
    'settings.shopName': 'Shop name', 'settings.startCash': 'Morning cash',
    'settings.startCashHint': 'Morning cash changes when a fresh day opens (close day first).',
    'settings.discount': 'Discounted sales allowed',
    'settings.discountHint': 'shows discount fields in Sell',
    'settings.refund': 'Refunds allowed', 'settings.refundHint': 'shows the refund feature',
    'settings.closeDay': 'Close today',
    'settings.export': 'Save backup (JSON)', 'settings.import': 'Restore backup (JSON)',
    'settings.reset': 'Wipe everything & start over',
    'settings.autosave': 'Everything auto-saves on every action. Backups are doubled inside the browser.',
    'settings.language': 'Interface language',

    'pin.title': 'Owner code', 'pin.wrong': 'Wrong code — try again',
    'pin.badFormat': 'The code is 4 to 6 digits only',
    'pin.saved': 'Owner code saved', 'pin.cleared': 'Owner lock removed',
    'pin.confirm': 'Type the current code to confirm',
    'pin.refund': 'Refund money — owner code?',
    'pin.day': 'Close the day — owner code?',
    'pin.undo': 'Undo last sale — owner code?',
    'pin.import': 'Import a full backup — owner code?',
    'pin.reset': 'Delete everything — owner code?',
    'pin.debt': 'Delete a debt — owner code?',
    'pin.fire': 'Fire an employee — owner code?',
    'pin.clear': 'Clear', 'pin.ok': 'OK',

    'toast.couldntSave': "Couldn't save",
    'toast.saleCancelled': 'Sale cancelled',
    'toast.saleOk': 'Sale recorded', 'toast.saleCredit': 'Recorded on credit: ',
    'toast.saleRest': 'Sale recorded, rest owed by: ',
    'toast.change': 'Give the customer this change:',
    'toast.paidBad': 'That paid amount is not valid',
    'toast.restName': 'The unpaid rest needs a customer name',
    'toast.freeName': 'Type the item name',
    'toast.freePrice': 'Price must be zero or more',
    'toast.freeQty': 'Qty must be at least 1',
    'toast.refundPick': 'Pick a product to refund',
    'toast.refundOk': 'Refund recorded',
    'toast.prodName': 'Type the product name', 'toast.prodPrice': 'Type the sell price',
    'toast.savedOk': 'Saved',
    'toast.debtName': 'Enter the name and amount', 'toast.debtOk': 'Debt recorded',
    'toast.amount': 'Enter an amount', 'toast.payOk': 'Payment recorded',
    'toast.payOver': 'That is more than the remaining debt: ',
    'toast.cashIn': 'Booked in the box', 'toast.cashOut': 'Booked out of the box',
    'toast.catAdded': 'Category added', 'toast.catDup': 'That category already exists',
    'toast.noStock': 'No stock left for this product',
    'toast.maxStock': "Can't take the basket over the stock: ",
    'toast.checkAmt': 'Enter the amount you counted', 'toast.checkOk': 'Count recorded',
    'toast.dayClosed': 'Day closed — a new one opened with the same cash',
    'toast.undoConfirm': 'Undo the last sale? Goods and cash come back, and any debt it created is removed.',
    'toast.undoOk': 'Last sale undone', 'toast.nothingUndo': 'No sale to undo',
    'toast.debtDeleted': 'Deleted from the record',
    'toast.resetConfirm': "Erase all shop data? This can't be undone. (Export a backup first)",
    'toast.resetOk': 'Fresh start',
    'toast.importConfirm': 'Restore this backup? Current shop data will be replaced immediately.',
    'toast.importOk': 'Backup restored', 'toast.importBad': 'This file is not a valid backup',
    'toast.restock': 'Added to stock',

    'receipt.title': 'Receipt', 'receipt.client': 'Customer',
    'receipt.close': 'Done', 'receipt.print': 'Print', 'receipt.thanks': 'Thank you for visiting',
    'receipt.total': 'Total', 'receipt.paid': 'Paid',

    'tab.employees': 'Staff', 'tab.monthly': 'Monthly',
    'staff.head': 'The team',
    'staff.sub': 'Your team and their wages — hire, edit, end contracts',
    'monthly.head': 'Monthly review', 'monthly.sub': 'Wins, losses and profit — salaries included',
    'staff.perMonth': 'per month',
    'staff.wins': 'Wins (in)', 'staff.losses': 'Losses (out)', 'staff.profit': 'Profit',
    'staff.sales': 'Sales', 'staff.debtPays': 'Debt payments', 'staff.incomes': 'Other income',
    'staff.refunds': 'Refunds', 'staff.buys': 'Stock buys', 'staff.expenses': 'Expenses',
    'staff.salaries': 'Salaries', 'staff.moves': 'moves', 'staff.dayInOut': 'in / out',
    'staff.team': 'The team',
    'staff.add': 'Add employee', 'staff.new': 'New employee', 'staff.edit': 'Edit',
    'staff.empty': 'No employees yet — hire your first',
    'staff.name': 'Name', 'staff.type': 'Type / role', 'staff.salary': 'Monthly salary',
    'staff.phone': 'Phone (optional)', 'staff.note': 'Note', 'staff.hired': 'Hired',
    'staff.fire': 'Fire', 'staff.fired': 'Fired',
    'toast.empSaved': 'Employee saved', 'toast.empFired': 'Employee fired',
    'toast.empFields': 'Name and type are required', 'toast.empSalary': 'Salary is not valid'
  };

  const T = {
    lang: 'ar',
    t: function (k) {
      const d = this.lang === 'ar' ? AR : EN;
      if (d[k] !== undefined) return d[k];
      if (AR[k] !== undefined) return AR[k];
      return k;
    },
    set: function (lang) {
      this.lang = (lang === 'en') ? 'en' : 'ar';
      try { localStorage.setItem(LS_LANG, this.lang); } catch (e) {}
      document.documentElement.lang = this.lang;
      document.documentElement.dir = this.lang === 'ar' ? 'rtl' : 'ltr';
      this.apply();
      window.dispatchEvent(new CustomEvent('dekkan:lang'));
    },
    apply: function () {
      var self = this;
      var els = document.querySelectorAll('[data-i18n]');
      for (var i = 0; i < els.length; i++) els[i].textContent = self.t(els[i].getAttribute('data-i18n'));
      var phs = document.querySelectorAll('[data-i18n-ph]');
      for (var j = 0; j < phs.length; j++) phs[j].setAttribute('placeholder', self.t(phs[j].getAttribute('data-i18n-ph')));
      var tis = document.querySelectorAll('[data-i18n-title]');
      for (var k = 0; k < tis.length; k++) tis[k].setAttribute('title', self.t(tis[k].getAttribute('data-i18n-title')));
    }
  };

  var saved = null;
  try { saved = localStorage.getItem(LS_LANG); } catch (e) {}
  T.lang = saved === 'en' ? 'en' : 'ar';

  // The shell ships RTL (index.html: <html lang="ar" dir="rtl">). A hard refresh
  // with English persisted used to restore only the TEXT — the document kept the
  // Arabic side until the user re-toggled. Declare the real direction here too,
  // on every boot, so the layout and the words always agree.
  document.documentElement.lang = T.lang;
  document.documentElement.dir = T.lang === 'ar' ? 'rtl' : 'ltr';

  window.T = T;
  // exposed for the i18n consistency check (node scripts/check-i18n.js)
  window.__DEKKAN_I18N__ = { AR: AR, EN: EN };
})();
